# Generated by Django 3.1.2 on 2020-10-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='first_name',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='faculty',
            name='last_name',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
